#
# ====================================================================
# Author: Jesse Bannon
# Date: 04/25/15
# Class: TCSS 342: Data Structures
# School: University of Washington Tacoma
# Desc: Uses Huffman Trees to compress text files.
# Copyright: Use for educational purposes only.
#====================================================================
#
CC=gcc
ARG=-lpthread
all: parser
parser:
	$(CC) -o Parse classroom_inspector.h util.h classroom_inspector.c main.c util.c $(ARG)
#
